version: "3.3"

services:
  database:
    container_name: LOJA-ONLINE_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=davidson
      - POSTGRES_USER=davidson
    ports:
    - 5432:5432
     
