# Generated by Django 5.0.4 on 2024-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
