# Generated by Django 5.0.4 on 2024-04-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='celular',
        ),
    ]
