# Generated by Django 5.0.2 on 2024-03-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infantil',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Infantil',
        ),
    ]
