# Generated by Django 5.0.6 on 2024-05-07 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho_acessorio",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho_calcado",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho_camisa",
        ),
    ]
