# Generated by Django 5.0.4 on 2024-04-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
