# Generated by Django 5.0.2 on 2024-04-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
    ]
