# Generated by Django 5.0.2 on 2024-03-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_delete_infantil_remove_produto_infantil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='slug',
            new_name='nome',
        ),
    ]
