# Generated by Django 5.0.6 on 2024-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_remove_produto_tamanho_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=16)),
            ],
            options={
                "ordering": ["descricao"],
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="tamanhos",
            field=models.ManyToManyField(blank=True, null=True, to="produtos.tamanho"),
        ),
    ]
