# Generated by Django 5.0.6 on 2024-05-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_tamanho_produto_tamanhos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
