# Generated by Django 5.0.2 on 2024-04-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_categoria/'),
        ),
    ]
