# Generated by Django 5.0.2 on 2024-04-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_tamanho_nome_tamanho_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='Tamanho',
        ),
        migrations.AddField(
            model_name='carrinhoitem',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
