# Generated by Django 5.0.2 on 2024-04-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_carrinho_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='imagem',
        ),
    ]
