# Generated by Django 5.0.4 on 2024-04-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
