# Generated by Django 5.0.2 on 2024-03-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_valor_produto_subtotal_produto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='total',
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
