# Generated by Django 5.0.2 on 2024-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produto_subtotal_remove_produto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_categoria/'),
        ),
    ]
