# Generated by Django 5.0.4 on 2024-04-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
