# Generated by Django 5.0.2 on 2024-02-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=32)),
                ('nome', models.SlugField(max_length=32)),
                ('preco', models.CharField(max_length=32)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
