# Generated by Django 5.0.2 on 2024-03-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivos', '0002_categoria_produto_delete_masculino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
