# Generated by Django 3.2.24 on 2024-02-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Masculino',
            new_name='Femenina',
        ),
    ]
