# Generated by Django 5.0.4 on 2024-04-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
